### PR TITLE
make sure to setup `PUT` correctly

### LINKED ISSUE #9: Documentation of put/post method
It is for me not obvious what `content` the put and post methods expect by default and the example code does not cover it. Is this expected to be form encoded or is the library doing some encoding? Is the client expected to set a header that covers this? I am trying to replicate  

```
curl http://example.com -XPUT -d value="hello"
```

and the question arises what the client needs to do. I suspect ` Uri.encoded_of_query` is the answer. Is it required to set the content type explicitly? Is it possible to observe  what the library is sending?

### PR DESCRIPTION
**Pull request by c-cube**
follow https://curl.se/libcurl/c/CURLOPT_UPLOAD.html and also set
the method to PUT.

close #9

### CODE REVIEW

**Comment by c-cube** [comment]
@lindig sorry for the delay. Would you mind trying this, please?

**Comment by c-cube** [comment]
testing locally, the diff is that with a body `` `String "hello"``, this gives me `content-length: 5` instead of `transfer-encoding: chunked`!

**Comment by lindig** [comment]
Thanks for the update. I don't have the exact code in front of my any longer but will test this patch in my current code.

**Comment by lindig** [comment]
By the way: the example require the containers package, which is not mentioned in the opam file. I think this is fine as long as it not builds by default.

**Comment by c-cube** [comment]
The example is not meant to be built by default (nor installed), indeed. If one day we get dev-dependencies we'll declare these deps there.

**Comment by lindig** [comment]
I tested the patch with my current code that is using `put` and it works.

```
  
let headers =
    [
      ("Content-Type", "application/x-www-form-urlencoded")
    ; ("Xapi", "xapi/etcdsh")
    ]
l

let put host port path value =
    let url = Uri.make ~scheme ~host ~port ~path () |> Uri.to_string in
    let query = Uri.encoded_of_query [ ("value", [ value ]) ] in
    EZ.put ~config ~url ~headers ~content:(`String query) ()
    |> response_handler url |> JSON.from_string
```

**Pull request merged**
